name: randolina
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_typeahead: ^3.2.3
  firebase_messaging: ^11.1.0
  flutter_local_notifications: ^9.1.4
  tuple: ^2.0.0
  firebase_core: ^1.4.0
  rename: ^1.3.1
  firebase_auth: ^3.0.0
  provider: ^5.0.0
  cloud_firestore: ^2.4.0
  logging: ^1.0.1
  firebase_storage: ^10.0.1
  uuid: 3.0.4
  sn_progress_dialog: ^1.0.2
  multiselect_formfield: 
    path: ./local_packages/multiselect_formfield
  font_awesome_flutter: ^9.1.0
  bordered_text: ^2.0.0
  algolia: ^1.0.1
  auto_size_text: ^3.0.0-nullsafety.0
  readmore: ^2.1.0
  cached_network_image: ^3.1.0
  rxdart: ^0.26.0
  carousel_slider: ^4.0.0
  get_time_ago: ^1.0.3
  flare_flutter: ^3.0.2
  cloud_functions: ^3.0.0
  paginate_firestore: ^1.0.2
  video_player: ^2.1.12
  better_player: ^0.0.72
  path_provider: ^2.0.2
  image_gallery_saver: ^1.6.9
  dio: ^4.0.0
  awesome_dropdown: ^0.0.4
  permission_handler: ^8.1.4+2
  fluttertoast: ^8.0.1-nullsafety.0
  story:
    path: ./local_packages/story
  photo_view: ^0.12.0
  youtube_plyr_iframe: ^2.0.7
  flutter_native_splash: ^1.2.1
  path: ^1.8.0
  date_time_picker: ^2.1.0
  #! need ios config
  url_launcher: ^6.0.9
  multi_image_picker2: ^5.0.2
  image_picker: ^0.8.2
  #!
  blur: ^3.0.0
  flutter_hsvcolor_picker: ^1.2.1
  intl: ^0.17.0
  ndialog: ^4.1.0
  syncfusion_flutter_sliders: ^19.2.59
  image_cropper: ^1.4.1
  camera: ^0.9.2+2
  liquid_swipe: ^2.1.0
  wechat_assets_picker: ^6.0.4
  video_thumbnail: ^0.4.3
  multi_select_flutter: ^4.0.0
  photofilters: ^3.0.1
  pull_to_refresh: ^2.0.0
  flutter_exif_rotation: ^0.4.1
  flutter_image_compress: ^1.1.0
  menu_button: ^1.4.2+1
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  open_file: ^3.2.1



  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  lint: ^1.5.3
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/sign_up/
    - assets/sign_up/icons/
    - assets/sign_up/backgrounds/
    - assets/sign_up/tiles/
    - assets/sign_up/icons/
    - assets/images/
    - assets/icons/
    - assets/flare/
    - assets/icons_final/
    - assets/camera_images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: LondrinaSolid-Regular
      fonts:
        - asset: assets/fonts/LondrinaSolid-Regular.ttf
    - family: Lato-Light
      fonts:
        - asset: assets/fonts/Lato-Light.ttf
    - family: Lato-Black
      fonts:
        - asset: assets/fonts/Lato-Black.ttf
    - family: Lato-Bloc
      fonts:
        - asset: assets/fonts/Lato-Bold.ttf
    - family: Poppins-Light
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
